import type { ProgramAutoData, ProgramItem2, ProgramSectionData, Programs2Data } from './types'

export const PROGRAM_GRADIENTS = [
  'linear-gradient(135deg,#14b8a6,#0d9488)',
  'linear-gradient(135deg,#3b82f6,#6366f1)',
  'linear-gradient(135deg,#8b5cf6,#7c3aed)',
  'linear-gradient(135deg,#f97316,#eab308)',
  'linear-gradient(135deg,#ec4899,#f43f5e)',
  'linear-gradient(135deg,#22c55e,#10b981)',
]

export const defaultProgramSectionData: ProgramSectionData = {
  layout: 'grid',
  titleVariant: 'badge',
  sectionBadge: '🏋️ Training Programs',
  sectionBadgeRu: '🏋️ Программы тренировок',
  sectionTitle: 'Pick your program',
  sectionTitleRu: 'Выберите свою программу',
  sectionSubtitle: '',
  sectionSubtitleRu: '',
  sectionDescription: 'Week-by-week plans built around your goal, level and equipment.',
  sectionDescriptionRu: 'Понедельные планы под вашу цель, уровень и оборудование.',
  bgType: 'solid',
  bgColor: '#0a0a0a',
  bgGradient: 'linear-gradient(135deg,#0a0a0a,#18181b)',
  cardBg: '#171717',
  cardBorder: 'rgba(255,255,255,0.06)',
  textColor: '#fafafa',
  accentColor: '#2dd4bf',
  columns: 3,
  gap: 28,
  slidesPerView: 3,
  showArrows: true,
  showDots: true,
  carouselSpeed: 40,
  carouselCardWidth: 320,
  showImage: true,
  showBadges: true,
  showMeta: true,
  showFeatures: true,
  showPrice: true,
  showButton: true,
  featuresLimit: 4,
}

export const defaultProgramAutoData = (): ProgramAutoData => ({
  section: { ...defaultProgramSectionData },
  limit: 0,
  sort: 'newest',
  ctaText: 'View program',
  ctaTextRu: 'Смотреть программу',
})

export const defaultProgramItems2: ProgramItem2[] = [
  {
    id: 'p1',
    title: 'Full Body Reset',
    titleRu: 'Перезапуск тела',
    description: 'An 8-week full body plan to rebuild strength and habits from scratch.',
    descriptionRu: 'Восьминедельный план на всё тело: возвращаем силу и режим с нуля.',
    price: 2900,
    currency: '$',
    duration: '8 weeks',
    durationRu: '8 недель',
    workouts: 24,
    goal: 'General',
    goalRu: 'Общая',
    difficulty: 'Beginner',
    difficultyRu: 'Начинающий',
    icon: '🔥',
    gradient: PROGRAM_GRADIENTS[0],
    features: ['3 workouts a week', 'Video for every exercise', 'Progress tracking'],
    featuresRu: ['3 тренировки в неделю', 'Видео к каждому упражнению', 'Отслеживание прогресса'],
    btn1: { text: 'View program', textRu: 'Смотреть программу', link: '/programs', style: 'primary' },
    btn2: { text: '', textRu: '', link: '', style: 'ghost' },
    popular: true,
  },
  {
    id: 'p2',
    title: 'Core & Posture',
    titleRu: 'Пресс и осанка',
    description: 'Six weeks of focused work on the deep core, back and posture.',
    descriptionRu: 'Шесть недель точечной работы над глубокими мышцами, спиной и осанкой.',
    price: 2400,
    currency: '$',
    duration: '6 weeks',
    durationRu: '6 недель',
    workouts: 18,
    goal: 'Recovery',
    goalRu: 'Восстановление',
    difficulty: 'Intermediate',
    difficultyRu: 'Средний',
    icon: '🧘',
    gradient: PROGRAM_GRADIENTS[1],
    features: ['Short 30-minute sessions', 'No equipment needed', 'Mobility warm-ups'],
    featuresRu: ['Короткие сессии по 30 минут', 'Без оборудования', 'Разминки на подвижность'],
    btn1: { text: 'View program', textRu: 'Смотреть программу', link: '/programs', style: 'primary' },
    btn2: { text: '', textRu: '', link: '', style: 'ghost' },
  },
  {
    id: 'p3',
    title: 'Strength Builder',
    titleRu: 'Набор силы',
    description: 'Twelve weeks of progressive overload for the gym.',
    descriptionRu: 'Двенадцать недель прогрессии нагрузки для зала.',
    price: 3900,
    oldPrice: 5900,
    currency: '$',
    duration: '12 weeks',
    durationRu: '12 недель',
    workouts: 48,
    goal: 'Muscle Gain',
    goalRu: 'Набор массы',
    difficulty: 'Advanced',
    difficultyRu: 'Продвинутый',
    icon: '💪',
    gradient: PROGRAM_GRADIENTS[2],
    features: ['4 workouts a week', 'Weight progression', 'Deload weeks'],
    featuresRu: ['4 тренировки в неделю', 'Прогрессия весов', 'Разгрузочные недели'],
    btn1: { text: 'View program', textRu: 'Смотреть программу', link: '/programs', style: 'primary' },
    btn2: { text: '', textRu: '', link: '', style: 'ghost' },
  },
]

export const defaultPrograms2Data = (): Programs2Data => ({
  section: { ...defaultProgramSectionData },
  items: defaultProgramItems2.map(i => ({ ...i, features: [...i.features], featuresRu: [...i.featuresRu], btn1: { ...i.btn1 }, btn2: { ...i.btn2 } })),
})
