import type { AboutSectionData, AboutContentBlock } from './types'

export const defaultAboutBlocks: AboutContentBlock[] = [
  {
    id: 'certs',
    type: 'grid-list',
    icon: '01',
    title: '🏆 Professional Qualifications',
    titleRu: '🏆 Квалификация',
    text: '',
    textRu: '',
    items: ["Master's in Physical Culture", 'NASM Certified Personal Trainer', 'CES, PBC, CNSC Specialist', 'Pre/Post-Natal Fitness Expert', 'Rehabilitation Specialist'],
    itemsRu: ['Магистр физической культуры', 'Сертифицированный тренер NASM', 'Специалист CES, PBC, CNSC', 'Пре/постнатальный фитнес', 'Реабилитолог'],
    stats: [],
    ctaText: '',
    ctaTextRu: '',
    ctaLink: '',
    bgStyle: 'dark',
  },
  {
    id: 'career',
    type: 'list',
    icon: '02',
    title: '🏅 Career & Achievements',
    titleRu: '🏅 Карьера и достижения',
    text: '',
    textRu: '',
    items: ['🥈 Olympia & Arnold Classic Amateur', '🏆 5× NPC Champion', '🥇 NPC National Gold Medalist'],
    itemsRu: ['🥈 Олимпия и Арнольд Классик', '🏆 5× чемпион NPC', '🥇 Золото NPC National'],
    stats: [],
    ctaText: '',
    ctaTextRu: '',
    ctaLink: '',
    bgStyle: 'light',
  },
  {
    id: 'journey',
    type: 'stats',
    icon: '💪',
    title: 'Personal Journey',
    titleRu: 'Личный путь',
    text: 'Mom of 2. Based in Las Vegas. 17+ years of experience transforming lives through fitness.',
    textRu: 'Мама двоих детей. Лас-Вегас. 17+ лет трансформации жизней через фитнес.',
    items: [],
    itemsRu: [],
    stats: [
      { value: '17+', label: 'Years', labelRu: 'Лет опыта' },
      { value: '1000+', label: 'Clients', labelRu: 'Клиентов' },
      { value: '5×', label: 'Champion', labelRu: 'Чемпион' },
    ],
    ctaText: 'Start Training →',
    ctaTextRu: 'Начать тренировки →',
    ctaLink: '/auth/register',
    bgStyle: 'accent',
  },
]

export const defaultAboutSectionData: AboutSectionData = {
  layout: 'classic',
  animation: 'fade-up',
  titleVariant: 'badge',
  image: '/images/hero-alexandra.jpg',
  imagePosition: 'left',
  name: 'Aleksandra Khavanskaia',
  sectionLabel: 'ABOUT THE TRAINER',
  sectionLabelRu: 'О ТРЕНЕРЕ',
  tagline: 'Coach. Athlete. Mom.',
  taglineRu: 'Тренер. Спортсменка. Мама.',
  tags: ['COACH', 'ATHLETE', 'MOM'],
  tagsRu: ['ТРЕНЕР', 'АТЛЕТ', 'МАМА'],
  bgType: 'solid',
  bgColor: '#0a0a0a',
  bgGradient: 'linear-gradient(135deg,#0a0a0a,#18181b)',
  textColor: '#fafafa',
  accentColor: '#2dd4bf',
  cardBg: '#171717',
  blocks: defaultAboutBlocks,
}
