import type { CourseItem2, CourseSectionData } from './types'

export const COURSE_GRADIENTS = [
  'linear-gradient(135deg,#ec4899,#f43f5e)',
  'linear-gradient(135deg,#8b5cf6,#7c3aed)',
  'linear-gradient(135deg,#3b82f6,#6366f1)',
  'linear-gradient(135deg,#14b8a6,#0d9488)',
  'linear-gradient(135deg,#f97316,#eab308)',
  'linear-gradient(135deg,#22c55e,#10b981)',
  'linear-gradient(135deg,#ef4444,#dc2626)',
  'linear-gradient(135deg,#06b6d4,#0891b2)',
  'linear-gradient(135deg,#a855f7,#7c3aed)',
]

export const defaultCourseSectionData: CourseSectionData = {
  layout: 'grid',
  titleVariant: 'badge',
  sectionBadge: '🎬 Expert Video Courses',
  sectionBadgeRu: '🎬 Экспертные видеокурсы',
  sectionTitle: 'Specialized Recovery',
  sectionTitleRu: 'Специализированное восстановление',
  sectionSubtitle: '',
  sectionSubtitleRu: '',
  sectionDescription: 'Clinically inspired, trainer-led recovery programs for the modern woman.',
  sectionDescriptionRu: 'Клинически обоснованные программы восстановления под руководством тренера.',
  bgType: 'solid',
  bgColor: '#0a0a0a',
  bgGradient: 'linear-gradient(135deg,#0a0a0a,#18181b)',
  cardBg: '#171717',
  cardBorder: 'rgba(255,255,255,0.06)',
  textColor: '#fafafa',
  accentColor: '#2dd4bf',
  columns: 2,
  gap: 28,
  autoplay: false,
  slidesPerView: 2,
}

export const defaultCourseItems2: CourseItem2[] = [
  {
    id: 'mammoplasty',
    title: 'Post-Mammoplasty Recovery',
    titleRu: 'Восстановление после маммопластики',
    description: 'Safe recovery and active lifestyle after breast surgery',
    descriptionRu: 'Безопасное восстановление и активный образ жизни',
    price: 99,
    oldPrice: 149,
    currency: '$',
    duration: '6 weeks',
    durationRu: '6 недель',
    lessons: 18,
    icon: '💗',
    gradient: 'linear-gradient(135deg,#ec4899,#f43f5e)',
    features: ['Safe scar exercises', 'Posture correction', 'Return to training', 'Expert guidance'],
    featuresRu: ['Работа с рубцом', 'Коррекция осанки', 'Возврат к тренировкам', 'Экспертное сопровождение'],
    btn1: { text: 'Buy Now', textRu: 'Купить', link: '/courses/mammoplasty', style: 'primary' },
    btn2: { text: 'Details', textRu: 'Подробнее', link: '/courses/mammoplasty', style: 'outline' },
    badge: 'Bestseller',
    badgeRu: 'Хит продаж',
    popular: true,
  },
  {
    id: 'csection',
    title: 'Post C-Section Recovery',
    titleRu: 'Восстановление после кесарева',
    description: 'Gentle, progressive recovery for new moms after surgery',
    descriptionRu: 'Мягкое и постепенное восстановление для мам после операции',
    price: 99,
    oldPrice: 149,
    currency: '$',
    duration: '8 weeks',
    durationRu: '8 недель',
    lessons: 24,
    icon: '👶',
    gradient: 'linear-gradient(135deg,#8b5cf6,#7c3aed)',
    features: ['Core rehabilitation', 'Diastasis recovery', 'Pelvic floor training', 'Safe return to activity'],
    featuresRu: ['Реабилитация кора', 'Восстановление диастаза', 'Тренировка тазового дна', 'Безопасный возврат'],
    btn1: { text: 'Buy Now', textRu: 'Купить', link: '/courses/csection', style: 'primary' },
    btn2: { text: 'Details', textRu: 'Подробнее', link: '/courses/csection', style: 'outline' },
  },
]
